/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jni.h"
/* Header for class ndk1_Simple3 */

#ifndef _Included_ndk1_Simple3
#define _Included_ndk1_Simple3
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ndk1_Simple3
 * Method:    changeage
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_ndk1_Simple3_changeage
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
